"""Generează DDL-ul complet al schemei `public` din baza LIVE.

De ce există: consolidarea manuală a `docs/schema_v2_production.sql` (829 linii) cu cele 42 de
migrări delta (2.455 linii) pierde tăcut detalii — un CHECK adăugat într-o migrare, o coloană
generated, o politică RLS rescrisă. Baza live ARE toate migrările aplicate, deci ea e sursa de
adevăr, nu suma fișierelor.

Nu e un pg_dump complet și nici nu încearcă să fie: emite exact ce ne trebuie ca să reconstruim
schema `public` pe un proiect Supabase nou — tabele (inclusiv partiționate), constrângeri, indexuri,
funcții proprii, triggere, RLS + politici, granturi pentru rolurile noastre, comentarii.

Ce EXCLUDE deliberat, și de ce:
  • obiectele deținute de extensii (pgvector, pg_trgm) — se recreează prin `create extension`;
  • partițiile individuale (`messages_2026_08`) — sunt date de calendar, le creează
    `jobs/partition_maintenance.py`; parintele partiționat se emite;
  • schemele Supabase interne (`auth`, `storage`, `realtime`) — le creează platforma.

Rulare:
    python scripts/dump_schema_ddl.py > docs/schema_v3_generated.sql
    python scripts/dump_schema_ddl.py --stats     # doar inventarul, pe stderr
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sys

import asyncpg

SCHEMA = "public"


def w(s: str = "") -> None:
    """Scrie o linie de DDL cu terminații LF, indiferent de platformă.

    Fără normalizare, pe Windows se produce o dublare tăcută: corpurile funcțiilor din baza
    sursă conțin deja `\\r\\n` (au fost create dintr-un fișier scris pe Windows), iar `print`
    traduce încă o dată `\\n` în `\\r\\n`, deci corpul ajunge cu `\\r\\r\\n`. Funcția se comportă
    identic, dar definiția nu mai e byte-identică, iar fiecare regenerare ulterioară raportează
    drift care nu există. Aceeași grijă o are și `scripts/migrate.py` la calculul checksumurilor,
    din exact același motiv.
    """
    sys.stdout.write(s.replace("\r\n", "\n") + "\n")


def ch(v: object) -> str:
    """Normalizează o coloană Postgres de tip `"char"`.

    asyncpg o întoarce ca `bytes`, iar valoarea „goală" e `b'\\x00'`, NU `b''` — deci un test
    de adevăr naiv (`if row["attidentity"]`) e adevărat pentru ORICE coloană și emite
    `generated by default as identity` peste tot, inclusiv pe `uuid`, unde nici nu e legal.
    """
    if isinstance(v, (bytes, bytearray)):
        v = v.decode("utf-8", "replace")
    return (v or "").replace("\x00", "").strip()


def q(ident: str) -> str:
    """Ghilimelează un identificator care nu e un `lowercase_snake` simplu.

    Politicile RLS moștenite din schema_v2 au nume cu spații („member read"), iar fără
    ghilimele DDL-ul generat nu se parsează.
    """
    if ident.isidentifier() and ident.islower() and not ident.startswith("_"):
        return ident
    return '"' + ident.replace('"', '""') + '"'


def banner(title: str) -> None:
    w()
    w("-- " + "=" * 74)
    w(f"-- {title}")
    w("-- " + "=" * 74)
    w()


async def extensions(conn: asyncpg.Connection) -> None:
    banner("EXTENSII")
    rows = await conn.fetch(
        """select e.extname, n.nspname
           from pg_extension e join pg_namespace n on n.oid = e.extnamespace
           where e.extname not in ('plpgsql')
           order by 1"""
    )
    for r in rows:
        w(f'create extension if not exists "{r["extname"]}" with schema {r["nspname"]};')


async def own_functions(conn: asyncpg.Connection, *, after_tables: bool) -> None:
    """Funcțiile NOASTRE (fără cele ale extensiilor), în DOUĂ treceri.

    Ordinea nu e o preferință, e o constrângere circulară reală:

      • unele TABELE depind de funcții — `products.search_tsv` e o coloană generated care
        cheamă `ro_unaccent()`, deci funcția trebuie să existe înainte de `create table`;
      • unele FUNCȚII depind de tabele — `in_24h_window(conv conversations)` primește tipul
        COMPOZIT al tabelului `conversations`, care nu există până nu există tabelul.

    `check_function_bodies = off` rezolvă doar prima jumătate (corpul), nu SEMNĂTURA: un tip
    de argument inexistent e eroare oricum. Deci separăm după dependență, nu după alfabet.
    """
    label = "FUNCȚII care depind de tabele" if after_tables else "FUNCȚII fără dependențe de tabele"
    banner(label)
    rows = await conn.fetch(
        """select p.proname, pg_get_functiondef(p.oid) as def,
                  exists (
                    select 1
                    from unnest(p.proargtypes::oid[] || p.prorettype) as t(typeoid)
                    join pg_type ty on ty.oid = t.typeoid
                    join pg_class rel on rel.oid = ty.typrelid
                    where rel.relkind in ('r','p','v','m')
                  ) as needs_tables
           from pg_proc p
           join pg_namespace n on n.oid = p.pronamespace
           where n.nspname = $1
             and not exists (
               select 1 from pg_depend d
               where d.objid = p.oid and d.deptype = 'e')
           order by p.proname""",
        SCHEMA,
    )
    emitted = [r for r in rows if bool(r["needs_tables"]) is after_tables]
    for r in emitted:
        w(r["def"].rstrip().rstrip(";") + ";")
        w()
    print(f"  {label.lower()}: {len(emitted)}", file=sys.stderr)


async def tables(conn: asyncpg.Connection) -> list[str]:
    """CREATE TABLE fără constrângeri de FK (se adaugă separat, ca ordinea să nu conteze)."""
    banner("TABELE")
    rels = await conn.fetch(
        """select c.oid, c.relname, c.relkind, c.relispartition,
                  case when c.relkind = 'p' then pg_get_partkeydef(c.oid) end as partkey
           from pg_class c join pg_namespace n on n.oid = c.relnamespace
           where n.nspname = $1
             and c.relkind in ('r','p')
             and not c.relispartition
             and not exists (
               select 1 from pg_depend d
               where d.objid = c.oid and d.deptype = 'e')
           order by c.relname""",
        SCHEMA,
    )
    names: list[str] = []
    for rel in rels:
        names.append(rel["relname"])
        cols = await conn.fetch(
            """select a.attname,
                      format_type(a.atttypid, a.atttypmod) as typ,
                      a.attnotnull,
                      pg_get_expr(d.adbin, d.adrelid) as def,
                      a.attgenerated,
                      a.attidentity
               from pg_attribute a
               left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
               where a.attrelid = $1 and a.attnum > 0 and not a.attisdropped
               order by a.attnum""",
            rel["oid"],
        )
        parts = []
        for c in cols:
            generated, identity = ch(c["attgenerated"]), ch(c["attidentity"])
            line = f"  {q(c['attname'])} {c['typ']}"
            if generated == "s":
                line += f" generated always as ({c['def']}) stored"
            elif identity:
                always = "always" if identity == "a" else "by default"
                line += f" generated {always} as identity"
            elif c["def"] is not None:
                line += f" default {c['def']}"
            if c["attnotnull"]:
                line += " not null"
            parts.append(line)
        suffix = f"\npartition by {rel['partkey']}" if rel["partkey"] else ""
        w(f"create table if not exists {rel['relname']} (")
        w(",\n".join(parts))
        w(f"){suffix};")
        w()
    print(f"  tabele: {len(names)}", file=sys.stderr)
    return names


async def constraints(conn: asyncpg.Connection) -> None:
    """PK / UNIQUE / CHECK / FK, în ordinea asta. FK la urmă ca ordinea tabelelor să nu conteze."""
    banner("CONSTRÂNGERI")
    for kinds, label in ((("p", "u", "c"), "PK / UNIQUE / CHECK"), (("f",), "CHEI STRĂINE")):
        w(f"-- {label}")
        rows = await conn.fetch(
            """select c.relname as tbl, con.conname, pg_get_constraintdef(con.oid) as def
               from pg_constraint con
               join pg_class c on c.oid = con.conrelid
               join pg_namespace n on n.oid = c.relnamespace
               where n.nspname = $1
                 and con.contype = any($2::char[])
                 and not c.relispartition
               order by c.relname, con.contype, con.conname""",
            SCHEMA,
            list(kinds),
        )
        for r in rows:
            w(f"alter table {q(r['tbl'])} add constraint {q(r['conname'])} {r['def']};")
        w()
        print(f"  constrangeri {label}: {len(rows)}", file=sys.stderr)


async def indexes(conn: asyncpg.Connection) -> None:
    """Indexuri care NU sunt în spatele unei constrângeri (alea vin cu constrângerea)."""
    banner("INDEXURI")
    rows = await conn.fetch(
        """select i.indexrelid::regclass::text as idx, pg_get_indexdef(i.indexrelid) as def
           from pg_index i
           join pg_class c on c.oid = i.indrelid
           join pg_namespace n on n.oid = c.relnamespace
           where n.nspname = $1
             and not c.relispartition
             and not exists (
               select 1 from pg_constraint con where con.conindid = i.indexrelid)
           order by 1""",
        SCHEMA,
    )
    for r in rows:
        w(
            r["def"]
            .replace("CREATE INDEX ", "create index if not exists ", 1)
            .replace("CREATE UNIQUE INDEX ", "create unique index if not exists ", 1)
            + ";"
        )
    print(f"  indexuri: {len(rows)}", file=sys.stderr)


async def triggers(conn: asyncpg.Connection) -> None:
    banner("TRIGGERE")
    rows = await conn.fetch(
        """select t.tgname, pg_get_triggerdef(t.oid) as def
           from pg_trigger t
           join pg_class c on c.oid = t.tgrelid
           join pg_namespace n on n.oid = c.relnamespace
           where n.nspname = $1 and not t.tgisinternal and not c.relispartition
           order by c.relname, t.tgname""",
        SCHEMA,
    )
    for r in rows:
        w(r["def"] + ";")
    print(f"  triggere: {len(rows)}", file=sys.stderr)


async def rls(conn: asyncpg.Connection) -> None:
    banner("RLS + POLITICI")
    rls_on = await conn.fetch(
        """select c.relname from pg_class c join pg_namespace n on n.oid = c.relnamespace
           where n.nspname = $1 and c.relrowsecurity and not c.relispartition
           order by 1""",
        SCHEMA,
    )
    for r in rls_on:
        w(f"alter table {r['relname']} enable row level security;")
    w()
    pols = await conn.fetch(
        """select tablename, policyname, permissive, roles, cmd, qual, with_check
           from pg_policies where schemaname = $1
           order by tablename, policyname""",
        SCHEMA,
    )
    for p in pols:
        roles = ", ".join(q(r) for r in p["roles"]) if p["roles"] else "public"
        perm = "permissive" if p["permissive"] == "PERMISSIVE" else "restrictive"
        line = (
            f"create policy {q(p['policyname'])} on {q(p['tablename'])}\n"
            f"  as {perm} for {p['cmd'].lower()} to {roles}"
        )
        if p["qual"]:
            line += f"\n  using ({p['qual']})"
        if p["with_check"]:
            line += f"\n  with check ({p['with_check']})"
        w(line + ";")
    print(f"  tabele cu RLS: {len(rls_on)} | politici: {len(pols)}", file=sys.stderr)


async def grants(conn: asyncpg.Connection) -> None:
    """DOAR rolurile noastre. Granturile Supabase (anon/authenticated) le pune platforma."""
    banner("GRANTURI (rolurile noastre)")
    ours = ("bot_runtime", "gdpr_svc", "dashboard_user")
    rows = await conn.fetch(
        """select grantee, table_name,
                  string_agg(distinct privilege_type, ', ' order by privilege_type) privs
           from information_schema.role_table_grants
           where table_schema = $1 and grantee = any($2::text[])
           group by 1, 2 order by 1, 2""",
        SCHEMA,
        list(ours),
    )
    for r in rows:
        w(f"grant {r['privs'].lower()} on {r['table_name']} to {r['grantee']};")
    print(f"  granturi: {len(rows)}", file=sys.stderr)


async def comments(conn: asyncpg.Connection) -> None:
    banner("COMENTARII")
    rows = await conn.fetch(
        """select c.relname as tbl, a.attname as col, d.description
           from pg_description d
           join pg_class c on c.oid = d.objoid
           join pg_namespace n on n.oid = c.relnamespace
           left join pg_attribute a on a.attrelid = c.oid and a.attnum = d.objsubid
           where n.nspname = $1 and c.relkind in ('r','p') and not c.relispartition
           order by c.relname, d.objsubid""",
        SCHEMA,
    )
    for r in rows:
        target = f"{r['tbl']}.{r['col']}" if r["col"] else r["tbl"]
        kind = "column" if r["col"] else "table"
        body = r["description"].replace("'", "''")
        w(f"comment on {kind} {target} is '{body}';")
    print(f"  comentarii: {len(rows)}", file=sys.stderr)


async def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--stats", action="store_true", help="doar inventarul, fara DDL")
    args = ap.parse_args()

    dsn = os.environ.get("SUPABASE_DB_URL")
    if not dsn:
        try:
            from dotenv import load_dotenv

            load_dotenv()
            dsn = os.environ["SUPABASE_DB_URL"]
        except Exception:
            sys.exit("SUPABASE_DB_URL lipseste")

    conn = await asyncpg.connect(dsn, statement_cache_size=0)
    try:
        if args.stats:
            sys.stdout = open(os.devnull, "w")
        else:
            # A doua jumătate a normalizării din `w()`: fără asta, `sys.stdout.write` ar
            # traduce oricum `\n` la `\r\n` pe Windows, iar redirectarea în fișier ar reintroduce
            # exact diferența pe care tocmai am eliminat-o.
            sys.stdout.reconfigure(newline="\n")
        w("-- DDL generat din baza LIVE de `scripts/dump_schema_ddl.py`.")
        w("-- NU edita direct: regenereaza, apoi aplica peste el patch-ul din schema_v3.")
        migs = await conn.fetch("select version from schema_migrations order by version")
        w(f"-- migrari aplicate in sursa: {', '.join(m['version'] for m in migs)}")
        w()
        # Funcțiile se emit ÎNAINTEA tabelelor, fiindcă o coloană generated le cheamă
        # (`search_tsv` → `ro_unaccent`). Dar o funcție `language sql` care citește un tabel e
        # validată LA CREARE, iar `category_has_active_products` citește `categories`, care
        # încă nu există. Fără linia asta, aplicarea pică pe o dependență circulară de ordine.
        # Exact ce face și `pg_dump`, din exact același motiv.
        w("set check_function_bodies = off;")
        await extensions(conn)
        await own_functions(conn, after_tables=False)
        await tables(conn)
        await own_functions(conn, after_tables=True)
        await constraints(conn)
        await indexes(conn)
        await triggers(conn)
        await rls(conn)
        await grants(conn)
        await comments(conn)
        banner("PARTITII")
        w("-- Partitiile lunare NU se emit: sunt date de calendar.")
        w("-- Ruleaza `python -m src.jobs.partition_maintenance` dupa aplicarea schemei.")
    finally:
        await conn.close()


if __name__ == "__main__":
    asyncio.run(main())
